-- =============================================================================
-- Jaya Dhaba — Canonical Schema
-- Generated from models.py (SQLAlchemy ORM source of truth)
-- Target: PostgreSQL 15 (production) / SQLite (development via SQLAlchemy)
--
-- DO NOT EDIT THIS FILE to change the schema.
-- Edit backend/models.py and regenerate with:
--   cd backend && python -c "
--   from db import engine
--   from models import Base
--   Base.metadata.create_all(engine)
--   "
-- This file is for reference, documentation, and fresh Postgres deployments.
-- The application NEVER reads this file at runtime.
-- =============================================================================

-- Required Postgres extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- USERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email           VARCHAR(255) UNIQUE,
    phone           VARCHAR(20) UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20) NOT NULL DEFAULT 'customer', -- owner, manager, staff, customer
    loyalty_points  INTEGER NOT NULL DEFAULT 0,

    -- MFA & brute-force hardening
    mfa_secret      VARCHAR(32),
    mfa_enabled     BOOLEAN NOT NULL DEFAULT FALSE,
    login_attempts  INTEGER NOT NULL DEFAULT 0,
    locked_until    TIMESTAMPTZ,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ  -- soft delete
);

CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_phone ON users (phone);

-- =============================================================================
-- SESSIONS
-- =============================================================================
CREATE TABLE IF NOT EXISTS sessions (
    id                   UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id              UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    refresh_token_hash   VARCHAR(255) NOT NULL UNIQUE,
    expires_at           TIMESTAMPTZ NOT NULL,
    revoked              BOOLEAN NOT NULL DEFAULT FALSE,

    -- Layer 5: session metadata
    ip_address           VARCHAR(45) NOT NULL,
    user_agent           TEXT,
    device_fingerprint   VARCHAR(255),

    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sessions_refresh_token ON sessions (refresh_token_hash);

-- =============================================================================
-- MENU CATEGORIES
-- =============================================================================
CREATE TABLE IF NOT EXISTS menu_categories (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name            VARCHAR(100) NOT NULL UNIQUE,
    display_order   INTEGER NOT NULL DEFAULT 0,
    active          BOOLEAN NOT NULL DEFAULT TRUE,

    -- Per-category GST rates (India)
    cgst_rate       FLOAT NOT NULL DEFAULT 2.5,
    sgst_rate       FLOAT NOT NULL DEFAULT 2.5
);

-- =============================================================================
-- MENU ITEMS
-- =============================================================================
CREATE TABLE IF NOT EXISTS menu_items (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    category_id     UUID NOT NULL REFERENCES menu_categories(id),
    name            VARCHAR(255) NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    price           INTEGER NOT NULL,  -- in paisa (1 INR = 100 paisa)
    image_url       VARCHAR(500) NOT NULL DEFAULT '',
    dietary_tags    JSONB NOT NULL DEFAULT '[]',
    available       BOOLEAN NOT NULL DEFAULT TRUE,

    -- Detailed info
    ingredients     JSONB NOT NULL DEFAULT '[]',
    chef_note       TEXT NOT NULL DEFAULT '',
    spice_level     INTEGER NOT NULL DEFAULT 0,
    calories        INTEGER,
    protein_g       FLOAT,
    carbs_g         FLOAT,
    fat_g           FLOAT,
    model_url       VARCHAR(500),
    video_url       VARCHAR(500),
    pairing_ids     JSONB NOT NULL DEFAULT '[]',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ  -- soft delete
);

-- =============================================================================
-- TABLES (restaurant physical tables)
-- =============================================================================
CREATE TABLE IF NOT EXISTS tables (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    qr_token    VARCHAR(100) NOT NULL UNIQUE,
    label       VARCHAR(50) NOT NULL,
    capacity    INTEGER NOT NULL,
    active      BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_tables_qr_token ON tables (qr_token);

-- =============================================================================
-- ORDERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS orders (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_number        BIGSERIAL UNIQUE NOT NULL,
    user_id             UUID REFERENCES users(id),
    table_id            UUID NOT NULL REFERENCES tables(id),
    status              VARCHAR(20) NOT NULL DEFAULT 'pending',
        -- pending, confirmed, preparing, ready, served, cancelled
    prep_stage          VARCHAR(20) NOT NULL DEFAULT 'placed',
        -- placed, prepping, plating, served
    occasion            VARCHAR(50),

    idempotency_key     VARCHAR(100) NOT NULL UNIQUE,
    version             INTEGER NOT NULL DEFAULT 1,  -- optimistic locking

    -- Financials (in paisa)
    subtotal            INTEGER NOT NULL,
    tax                 INTEGER NOT NULL,
    total               INTEGER NOT NULL,
    loyalty_discount    INTEGER NOT NULL DEFAULT 0,

    -- Guest info (unauthenticated orders)
    guest_name          VARCHAR(100) NOT NULL DEFAULT '',
    guest_phone         VARCHAR(20) NOT NULL DEFAULT '',

    public_token_hash   VARCHAR(255) NOT NULL,
    order_type          VARCHAR(20) NOT NULL DEFAULT 'dine_in',
        -- dine_in, pickup, delivery
    pickup_time         TIMESTAMPTZ,

    status_history      JSONB NOT NULL DEFAULT '[]',
    confirmed_at        TIMESTAMPTZ,
    served_at           TIMESTAMPTZ,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_status     ON orders (status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders (created_at);
CREATE INDEX IF NOT EXISTS idx_orders_user_id    ON orders (user_id);

-- =============================================================================
-- ORDER ITEMS
-- =============================================================================
CREATE TABLE IF NOT EXISTS order_items (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    menu_item_id    UUID NOT NULL REFERENCES menu_items(id),
    qty             INTEGER NOT NULL,
    unit_price      INTEGER NOT NULL,  -- snapshot at time of order
    special_note    TEXT NOT NULL DEFAULT '',
    is_addon        BOOLEAN NOT NULL DEFAULT FALSE,
    addon_added_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id);

-- =============================================================================
-- PAYMENTS
-- =============================================================================
CREATE TABLE IF NOT EXISTS payments (
    id                          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id                    UUID NOT NULL UNIQUE REFERENCES orders(id),

    -- Razorpay
    razorpay_payment_id         VARCHAR(100) UNIQUE,
    razorpay_order_id           VARCHAR(100) UNIQUE,

    -- Stripe (future)
    stripe_payment_intent_id    VARCHAR(100) UNIQUE,
    stripe_event_id             VARCHAR(100),

    amount                      INTEGER NOT NULL,
    status                      VARCHAR(20) NOT NULL DEFAULT 'pending',
        -- pending, completed, failed, refunded
    failure_reason              TEXT,

    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_razorpay_order_id
ON payments (razorpay_order_id)
WHERE razorpay_order_id IS NOT NULL;

-- =============================================================================
-- LOYALTY LEDGER
-- =============================================================================
CREATE TABLE IF NOT EXISTS loyalty_ledger (
    id              SERIAL PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id),
    order_id        UUID REFERENCES orders(id),
    delta           INTEGER NOT NULL,
    balance_after   INTEGER NOT NULL,
    reason          VARCHAR(100) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- INVENTORY
-- =============================================================================
CREATE TABLE IF NOT EXISTS inventory_items (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    menu_item_id    UUID NOT NULL UNIQUE REFERENCES menu_items(id),
    quantity        FLOAT NOT NULL DEFAULT 0.0,
    reorder_level   FLOAT NOT NULL DEFAULT 10.0,
    unit            VARCHAR(20) NOT NULL DEFAULT 'units'
);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    inventory_item_id   UUID NOT NULL REFERENCES inventory_items(id),
    delta               FLOAT NOT NULL,
    type                VARCHAR(20) NOT NULL,
    reason              TEXT NOT NULL,
    created_by          UUID REFERENCES users(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- AUDIT LOG (append-only — never UPDATE or DELETE rows in this table)
-- =============================================================================
CREATE TABLE IF NOT EXISTS audit_log (
    id              SERIAL PRIMARY KEY,
    user_id         UUID REFERENCES users(id) ON DELETE SET NULL,
    action          VARCHAR(100) NOT NULL,
    entity_type     VARCHAR(50) NOT NULL,
    entity_id       VARCHAR(100) NOT NULL,
    payload         JSONB NOT NULL DEFAULT '{}',
    ip_address      VARCHAR(45) NOT NULL,
    user_agent      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_log_entity    ON audit_log (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id   ON audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created   ON audit_log (created_at DESC);

-- =============================================================================
-- CAMPAIGNS (discount codes)
-- =============================================================================
CREATE TABLE IF NOT EXISTS campaigns (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    title           VARCHAR(255) NOT NULL,
    type            VARCHAR(20) NOT NULL,   -- percentage, fixed
    value           INTEGER NOT NULL,
    min_order_value INTEGER NOT NULL DEFAULT 0,
    start_date      TIMESTAMPTZ NOT NULL,
    end_date        TIMESTAMPTZ NOT NULL,
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    usage_limit     INTEGER,
    usage_count     INTEGER NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_campaigns_code ON campaigns (code);

-- =============================================================================
-- RESERVATIONS
-- =============================================================================
CREATE TABLE IF NOT EXISTS reservations (
    id                  SERIAL PRIMARY KEY,
    user_id             UUID REFERENCES users(id),
    table_id            UUID NOT NULL REFERENCES tables(id),
    party_size          INTEGER NOT NULL,
    reserved_at         TIMESTAMPTZ NOT NULL,
    duration_minutes    INTEGER NOT NULL DEFAULT 120,
    status              VARCHAR(20) NOT NULL DEFAULT 'pending',
        -- pending, confirmed, cancelled
    guest_name          VARCHAR(120) NOT NULL,
    guest_phone         VARCHAR(40) NOT NULL,
    celebration_type    VARCHAR(50),
    idempotency_key     VARCHAR(100) UNIQUE,
    request_hash        VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- DISH RATINGS
-- =============================================================================
CREATE TABLE IF NOT EXISTS dish_ratings (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id        UUID NOT NULL REFERENCES orders(id),
    menu_item_id    UUID NOT NULL REFERENCES menu_items(id),
    user_id         UUID REFERENCES users(id),
    rating          INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment         TEXT,
    photo_url       VARCHAR(500),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (order_id, menu_item_id)
);

-- =============================================================================
-- VOUCHERS
-- =============================================================================
CREATE TABLE IF NOT EXISTS vouchers (
    id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code            VARCHAR(50) NOT NULL UNIQUE,
    initial_value   INTEGER NOT NULL,
    current_value   INTEGER NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_vouchers_code ON vouchers (code);

-- =============================================================================
-- REFERRALS
-- =============================================================================
CREATE TABLE IF NOT EXISTS referrals (
    id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    referrer_user_id    UUID NOT NULL REFERENCES users(id),
    referral_code       VARCHAR(20) NOT NULL UNIQUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reward_card_id      VARCHAR(100) UNIQUE,
    reward_type         VARCHAR(50),
    reward_claimed      BOOLEAN NOT NULL DEFAULT FALSE,
    reward_redeemed     BOOLEAN NOT NULL DEFAULT FALSE,
    redeemed_at         TIMESTAMPTZ,
    redeemed_by_admin   UUID REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_referrals_code ON referrals (referral_code);

-- =============================================================================
-- SITE SETTINGS (key-value store for dynamic config)
-- =============================================================================
CREATE TABLE IF NOT EXISTS site_settings (
    key         VARCHAR(100) PRIMARY KEY,
    value       TEXT NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- PRICING RULES
-- =============================================================================
CREATE TABLE IF NOT EXISTS pricing_rules (
    id              SERIAL PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    days_of_week    JSONB NOT NULL DEFAULT '[]',  -- [0,1,2,3,4,5,6]
    start_time      VARCHAR(10) NOT NULL,          -- "HH:MM"
    end_time        VARCHAR(10) NOT NULL,
    discount_type   VARCHAR(20) NOT NULL,          -- percentage, fixed
    discount_value  INTEGER NOT NULL,
    applies_to      VARCHAR(20) NOT NULL,          -- all, category, item
    applies_to_ids  JSONB NOT NULL DEFAULT '[]',
    active          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- PAIRING RULES
-- =============================================================================
CREATE TABLE IF NOT EXISTS pairing_rules (
    id                  SERIAL PRIMARY KEY,
    trigger_item_id     INTEGER,
    trigger_category    VARCHAR(100),
    suggested_item_ids  JSONB NOT NULL DEFAULT '[]',
    priority            INTEGER NOT NULL DEFAULT 0,
    active              BOOLEAN NOT NULL DEFAULT TRUE
);

-- =============================================================================
-- FEEDBACK
-- =============================================================================
CREATE TABLE IF NOT EXISTS feedback (
    id          SERIAL PRIMARY KEY,
    order_id    INTEGER NOT NULL UNIQUE,
    rating      INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     TEXT NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- CHAT LOG
-- =============================================================================
CREATE TABLE IF NOT EXISTS chat_log (
    id          SERIAL PRIMARY KEY,
    user_id     UUID REFERENCES users(id),
    session_id  VARCHAR(120) NOT NULL,
    role        VARCHAR(20) NOT NULL,  -- user, assistant
    message     TEXT NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_chat_log_session ON chat_log (session_id);

-- =============================================================================
-- DAILY CLOSURES (high-water mark for analytics reset)
-- The backend uses this table — NOT daily_analytics.
-- live_stats() queries: SELECT SUM(total) FROM orders WHERE created_at > MAX(closed_at)
-- POST /admin/flush inserts a new row here to "reset" the daily window.
-- APScheduler inserts automatically at midnight IST.
-- =============================================================================
CREATE TABLE IF NOT EXISTS daily_closures (
    id          SERIAL PRIMARY KEY,
    closed_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revenue     INTEGER NOT NULL DEFAULT 0,
    orders      INTEGER NOT NULL DEFAULT 0,
    created_by  UUID REFERENCES users(id) ON DELETE SET NULL
);

-- =============================================================================
-- SETTINGS (restaurant profile — singular row)
-- Separate from site_settings (key-value). This holds structured restaurant info.
-- =============================================================================
CREATE TABLE IF NOT EXISTS settings (
    id          INTEGER PRIMARY KEY DEFAULT 1,
    name        VARCHAR(120) NOT NULL DEFAULT 'Jaya Dhaba',
    tagline     VARCHAR(160) NOT NULL DEFAULT '',
    hours       VARCHAR(120) NOT NULL DEFAULT '9am - 11pm',
    contact     VARCHAR(40) NOT NULL DEFAULT '',
    status      VARCHAR(40) NOT NULL DEFAULT 'open',
    address     VARCHAR(240) NOT NULL DEFAULT '',
    tax_rate    INTEGER NOT NULL DEFAULT 5,
    currency    VARCHAR(10) NOT NULL DEFAULT 'INR',
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT settings_singleton CHECK (id = 1)
);

-- Ensure the singleton row always exists
INSERT INTO settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- CONTACT MESSAGES
-- =============================================================================
CREATE TABLE IF NOT EXISTS contact_messages (
    id                  SERIAL PRIMARY KEY,
    name                VARCHAR(120) NOT NULL,
    email               VARCHAR(255) NOT NULL,
    message             TEXT NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'new',
    idempotency_key     VARCHAR(100) UNIQUE,
    request_hash        VARCHAR(100),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =============================================================================
-- NOTE: The previous schema.sql defined daily_analytics + settle_daily_stats()
-- These are DEAD CODE. The backend never reads or writes daily_analytics.
-- They have been removed from this schema to avoid confusion during incident
-- response. The actual analytics mechanism is daily_closures + live_stats().
-- =============================================================================
